### ISSUE TITLE
undefined method `-' for nil:NilClass

### ISSUE THREAD

**Issue by jan** [afeld/mongoid-locker#18]
In the current HEAD version, I get `undefined method - for nil:NilClass` when calling

    self.with_lock timeout: 1.minute, wait: true, reload: true do

My backtrace is:

    /Users/me/.rvm/gems/ruby-1.9.3-p392/bundler/gems/mongoid-locker-19e6fccd5e38/lib/mongoid/locker.rb:143:in `lock'
    /Users/me/.rvm/gems/ruby-1.9.3-p392/bundler/gems/mongoid-locker-19e6fccd5e38/lib/mongoid/locker.rb:79:in `with_lock'
    /Users/me/Documents/Projects/priceapi_api/app/models/job.rb:89:in `handle_result'

This is the line

    retry_sleep = locked_until - Time.now

Which means, that `locked_until` is `nil` here.

**Comment by dblock** [comment]
This was fixed in https://github.com/afeld/mongoid-locker/pull/32.
