### ISSUE TITLE
Incompatible with Mongoid 3.1.6

### ISSUE THREAD

**Issue by franciscodelgadodev** [afeld/mongoid-locker#33]
Hi all,

I have a problem trying to install mongoid-locker gem in my project. I'm using Mongoid(3.1.6).
If I add this to my gemfile:

```ruby
gem 'mongoid-locker', '~> 0.2'
```

I get this error
```ruby
Bundler could not find compatible versions for gem "mongoid":
  In Gemfile:
    mongoid-locker (~> 0.2) ruby depends on
      mongoid (<= 3.1, >= 2.4) ruby

    mongoid (3.1.6)
```

And if I point to the newer versions in my Gemfile:
```ruby
gem 'mongoid-locker', '~> 0.3'
```

I get this error
```ruby
Bundler could not find compatible versions for gem "mongoid":
  In Gemfile:
    mongoid-locker (~> 0.3) ruby depends on
      mongoid (~> 4.0) ruby

    mongoid (3.1.6)
```

We're not planning to upgrade to Mongoid 4 yet, so I'd like to use the version ~> 0.2. I was looking into this problem and I found this issue https://github.com/afeld/mongoid-locker/issues/12 that seems to be the solution. However, if it was the solution before it's not working anymore.

I can create a PR to support Mongoid versions ~> 3.1.0 but I want to be sure I'm not missing something.

Thanks in advance,
Francisco.

**Comment by afeld** [comment]
Sorry, that was my bad...try upgrading to 0.3.2, which should work. The gem was actually compatible all along, but the gemspec was wrong.

**Comment by franciscodelgadodev** [comment]
Thank you
